### ISSUE TITLE
Building with gcc 7[.3.0] fails

### ISSUE THREAD

**Issue by mkreisl** [xbmc/imagedecoder.raw#17]
While building, gcc  7.3.0 complains error as follows:

```
internal/dcraw_common.cpp: In function ‘float _CanonConvertAperture(ushort)’:
internal/dcraw_common.cpp:5779:29: error: call of overloaded ‘powf64(double, double)’ is ambiguous
   return powf64(2.0, in/64.0);
                             ^ 
In file included from /usr/arm-linux-gnueabihf/include/c++/7/cmath:45:0,
                 from /usr/arm-linux-gnueabihf/include/c++/7/math.h:36, 
                 from internal/dcraw_common.cpp:22:
/usr/arm-linux-gnueabihf/include/bits/mathcalls.h:140:1: note: candidate: _Float64 powf64(_Float64, _Float64)
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
 ^
internal/dcraw_common.cpp:5755:14: note: candidate: float powf64(float, float)
 static float powf64(float a, float b)
              ^~~~~~
```
and stopped

Probably [this commit](https://github.com/LibRaw/LibRaw/commit/158398653a14e8b5884d744ec711ba31a8ceafdc#diff-57d551e41fc4f5d8039b03b38215ebc1) will fix the issue

**Comment by Lou-Cipher** [comment]
Yup, was just tracking down this issue, too.  0.18.8 resolves this, as per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891272

**Comment by Lou-Cipher** [comment]
I can verify that using LibRaw branch 0.18-stable allows this to build successfully.  Haven't yet verified functionality, but no build errors.

**Comment by Lou-Cipher** [comment]
Wanted to check on this, I'm still building successfully against 0.18-stable LibRaw, can we get a version bump of the tarball in kodi's build-depends repo?
